org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.6-beta

## Mod Properties
mod_id=petting
mod_name=Petting
mod_license=GNU LESSER GENERAL PUBLIC LICENSE Version 3
mod_version=5.0.0
mod_group_id=net.yigitguven.petting
mod_authors=Yigit Guven
mod_description=Break the limits of Minecraft taming. This mod introduces a universal Petting mechanic that allows you to tame any mob - whether vanilla or mods.

## Dependencies
jei_version=31.1.0.13
