modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/yigit-guven/Petting/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/yigit-guven/Petting"
logoFile="logo.png"
credits="Special thanks to Anchor Studios & Ryukazan for their contributions."
authors="Yigit Guven"
description="Break the limits of Minecraft taming. This mod introduces a universal Petting mechanic that allows you to tame any mob—whether vanilla or mods."

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="AFTER"
    side="BOTH"
