modLoader="javafml"
loaderVersion="[4,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="petting"
version="4.0.02"
displayName="Petting"
displayURL="https://github.com/yigit-guven/Petting"
logoFile="logo.png"
credits="Special thanks to Anchor Studios & Ryukazan for their contributions."
authors="Vuserr0"
description="Pet mobs and have them become protective companions that follow you, offering support and assistance during your adventures."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.petting]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.petting]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration