modLoader="javafml"
license="${mod_license}"
issueTrackerURL="https://github.com/yigit-guven/Petting/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/yigit-guven/Petting/main/update.json"
displayURL="https://github.com/yigit-guven/Petting"
logoFile="logo.png"
credits="Special thanks to Anchor Studios & Ryukazan for their contributions."
authors="${mod_authors}"
description='''
${mod_description}
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
